import React,{useEffect,useState} from 'react';
import {Alert,Modal,Platform,Pressable,ScrollView,StatusBar,StyleSheet,Text,TextInput,View} from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import * as Picker from 'expo-document-picker';
import {SafeAreaProvider,SafeAreaView} from 'react-native-safe-area-context';
import {extractText,isAvailable} from 'expo-pdf-text-extract';
import {parseCsv,parsePdfText,ImportedRow} from './statement-import';
type Tx={id:string;date:string;merchant:string;amount:number;kind:'expense'|'income';category:string;source?:string};type Data={name:string;cash:number;opening:number;budget:number;transactions:Tx[]};
const KEY='stillwell-mobile-v2',OLD='stillwell-mobile-v1',blank=():Data=>({name:'',cash:0,opening:0,budget:0,transactions:[]}),money=(n:number)=>'₹'+Math.round(Math.abs(n)).toLocaleString('en-IN'),today=()=>new Date().toISOString().slice(0,10);
function impact(d:Data,t:Tx,dir=1){d.cash+=(t.kind==='income'?1:-1)*t.amount*dir;return d;}
function App(){const [d,setD]=useState(blank),[page,setPage]=useState('Home'),[modal,setModal]=useState(''),[rows,setRows]=useState<ImportedRow[]>([]),[name,setName]=useState(''),[amt,setAmt]=useState(''),[kind,setKind]=useState<'expense'|'income'>('expense'),[cat,setCat]=useState('Other'),[edit,setEdit]=useState(''),[budget,setBudget]=useState(''),[loading,setLoading]=useState(false);
useEffect(()=>{(async()=>{try{let v=await AsyncStorage.getItem(KEY);if(v)setD(JSON.parse(v));else{const old=await AsyncStorage.getItem(OLD);if(old){const o=JSON.parse(old),n=blank();n.name=o.name||'';for(const x of (o.transactions||[]).filter((t:Tx)=>!String(t.id).startsWith('d'))){const t={...x,kind:x.kind==='income'?'income':'expense'} as Tx;n.transactions.push(t);impact(n,t);}await AsyncStorage.setItem(KEY,JSON.stringify(n));setD(n);}}}catch{} })();},[]);
const save=(x:Data)=>{setD({...x});AsyncStorage.setItem(KEY,JSON.stringify(x)).catch(()=>Alert.alert('Could not save','Device storage is unavailable.'));};
const month=d.transactions.filter(t=>t.date.slice(0,7)===today().slice(0,7)),spent=month.filter(t=>t.kind==='expense').reduce((a,t)=>a+t.amount,0),income=month.filter(t=>t.kind==='income').reduce((a,t)=>a+t.amount,0);
const start=()=>{setEdit('');setName('');setAmt('');setKind('expense');setCat('Other');setModal('entry');};
const saveTx=()=>{const a=Number(amt.replace(/,/g,''));if(!name.trim()||!a||a<0)return Alert.alert('Check details','Enter a description and a positive amount.');const n={...d,transactions:[...d.transactions]};if(edit){const i=n.transactions.findIndex(t=>t.id===edit);if(i>=0){impact(n,n.transactions[i],-1);n.transactions[i]={...n.transactions[i],merchant:name.trim(),amount:a,kind,category:cat};impact(n,n.transactions[i]);}}else{const t:Tx={id:'manual-'+Date.now(),date:today(),merchant:name.trim(),amount:a,kind,category:cat,source:'Manual'};n.transactions.push(t);impact(n,t);}save(n);setModal('');};
const importFile=async()=>{try{const f=await Picker.getDocumentAsync({type:['text/csv','text/comma-separated-values','application/pdf','text/plain'],copyToCacheDirectory:true});if(f.canceled)return;setLoading(true);const a=f.assets[0];let result:ImportedRow[];if(a.name.toLowerCase().endsWith('.pdf')||a.mimeType==='application/pdf'){if(!isAvailable())throw Error('PDF reading needs the installed native app.');result=parsePdfText(await extractText(a.uri),d.transactions);}else{const fs=await import('expo-file-system/legacy');result=parseCsv(await fs.readAsStringAsync(a.uri),d.transactions);}setRows(result);setModal('import');}catch(e:any){Alert.alert('Statement could not be read',e?.message||'Choose a CSV or text-based PDF.');}finally{setLoading(false);}};
const confirmImport=()=>{const n={...d,transactions:[...d.transactions]};const chosen=rows.filter(r=>r.selected);chosen.forEach(r=>{const t:Tx={id:r.id,date:r.date,merchant:r.merchant,amount:r.amount,kind:r.kind,category:r.category,source:'Statement'};n.transactions.push(t);impact(n,t);});if(!chosen.length)return Alert.alert('Nothing selected','Select at least one transaction.');save(n);setRows([]);setModal('');Alert.alert('Import complete',chosen.length+' transactions added.');};
const row=(t:Tx)=><Pressable key={t.id} style={s.tx} onPress={()=>{setEdit(t.id);setName(t.merchant);setAmt(String(t.amount));setKind(t.kind);setCat(t.category);setModal('entry');}} onLongPress={()=>Alert.alert('Delete transaction?',t.merchant,[{text:'Cancel'},{text:'Delete',style:'destructive',onPress:()=>{const n={...d,transactions:d.transactions.filter(x=>x.id!==t.id)};impact(n,t,-1);save(n);}}])}><View style={{flex:1}}><Text style={s.bold}>{t.merchant}</Text><Text style={s.muted}>{t.date} · {t.category} · {t.source||'Manual'}</Text></View><Text style={s.bold}>{t.kind==='income'?'+':'−'} {money(t.amount)}</Text></Pressable>;
return <SafeAreaProvider><SafeAreaView style={s.safe}><StatusBar barStyle="dark-content"/><View style={s.header}><Text style={s.brand}>STILLWELL · {page.toUpperCase()}</Text><Pressable onPress={()=>setModal('profile')}><Text style={s.avatar}>{d.name[0]?.toUpperCase()||'+'}</Text></Pressable></View><ScrollView contentContainerStyle={s.body} keyboardShouldPersistTaps="handled">
{page==='Home'?<><Text style={s.eyebrow}>YOUR MONEY, YOUR PICTURE</Text><Text style={s.title}>Welcome{d.name?', '+d.name:''}.</Text><Text style={s.muted}>Only data you enter or import appears here.</Text><View style={s.card}><Text style={s.eyebrow}>TRACKED BALANCE</Text><Text style={s.big}>{money(d.cash)}</Text><Text style={s.muted}>Opening balance plus transactions you recorded</Text><View style={s.line}/><Text style={s.label}>INCOME THIS MONTH     {money(income)}</Text><Text style={s.label}>SPENT THIS MONTH      {money(spent)}</Text></View><View style={s.card}><Text style={s.bold}>Start with a bank statement</Text><Text style={s.muted}>Import CSV or digital PDF. Review rows before saving.</Text><Pressable style={s.button} onPress={importFile}><Text style={s.white}>{loading?'Reading…':'Import statement'}</Text></Pressable></View><Text style={s.title2}>Recent activity</Text>{d.transactions.length?d.transactions.slice(-5).reverse().map(row):<Text style={s.muted}>No transactions yet. Add one or import your statement.</Text>}</>:page==='Activity'?<><Text style={s.eyebrow}>YOUR RECORDS</Text><Text style={s.title}>Transactions</Text><Text style={s.muted}>Tap to edit · hold to delete</Text><Pressable style={s.button} onPress={start}><Text style={s.white}>＋ Add transaction</Text></Pressable><Pressable style={s.outline} onPress={importFile}><Text style={s.dark}>{loading?'Reading…':'⇧ Import bank statement (CSV / PDF)'}</Text></Pressable>{d.transactions.length?[...d.transactions].sort((a,b)=>b.date.localeCompare(a.date)).map(row):<Text style={s.muted}>No transactions recorded yet.</Text>}</>:<><Text style={s.eyebrow}>YOUR MONTHLY PLAN</Text><Text style={s.title}>Spending budget</Text><View style={s.card}><Text style={s.label}>SPENT THIS MONTH</Text><Text style={s.big}>{money(spent)}</Text><Text style={s.label}>MONTHLY BUDGET (₹)</Text><TextInput style={s.input} keyboardType="numeric" value={budget||String(d.budget||'')} onChangeText={setBudget} onBlur={()=>{let b=Number(budget);if(b>=0)save({...d,budget:b});}} placeholder="Set your budget"/>{d.budget?<Text style={s.muted}>{money(Math.max(0,d.budget-spent))} remaining</Text>:<Text style={s.muted}>No sample budget is set.</Text>}</View></>}
</ScrollView><View style={s.nav}>{['Home','Activity','Plan'].map(t=><Pressable key={t} onPress={()=>setPage(t)}><Text style={[s.dark,page===t&&s.green]}>{t}</Text></Pressable>)}</View>
<Modal visible={modal==='entry'} transparent animationType="slide" onRequestClose={()=>setModal('')}><View style={s.overlay}><View style={s.sheet}><Pressable onPress={()=>setModal('')}><Text style={s.close}>Close ×</Text></Pressable><Text style={s.title}>{edit?'Edit':'Add'} transaction</Text><TextInput style={s.input} value={name} onChangeText={setName} placeholder="Description"/><TextInput style={s.input} value={amt} onChangeText={setAmt} keyboardType="decimal-pad" placeholder="Amount in ₹"/><View style={s.nav}>{(['expense','income'] as const).map(k=><Pressable key={k} onPress={()=>setKind(k)}><Text style={kind===k?s.green:s.dark}>{k.toUpperCase()}</Text></Pressable>)}</View><TextInput style={s.input} value={cat} onChangeText={setCat} placeholder="Category"/><Pressable style={s.button} onPress={saveTx}><Text style={s.white}>Save</Text></Pressable></View></View></Modal>
<Modal visible={modal==='import'} animationType="slide" onRequestClose={()=>setModal('')}><SafeAreaView style={s.safe}><View style={s.header}><Text style={s.brand}>REVIEW IMPORT</Text><Pressable onPress={()=>setModal('')}><Text style={s.dark}>Close</Text></Pressable></View><ScrollView contentContainerStyle={s.body}><Text style={s.title}>{rows.filter(r=>r.selected).length} of {rows.length} selected</Text><Text style={s.muted}>Tap checkbox to include or skip. Possible duplicates are unchecked. Edit descriptions inline. Nothing saves until confirmed.</Text>{rows.map(r=><View key={r.id} style={s.importRow}><Pressable onPress={()=>setRows(rows.map(x=>x.id===r.id?{...x,selected:!x.selected}:x))}><Text style={s.check}>{r.selected?'☑':'□'}</Text></Pressable><View style={{flex:1}}><TextInput style={s.editInput} value={r.merchant} onChangeText={v=>setRows(rows.map(x=>x.id===r.id?{...x,merchant:v}:x))}/><Text style={s.muted}>{r.date} · {r.category}{r.duplicate?' · POSSIBLE DUPLICATE':''}</Text></View><Text style={s.bold}>{r.kind==='income'?'+':'−'}{money(r.amount)}</Text></View>)}<Pressable style={s.button} onPress={confirmImport}><Text style={s.white}>Import selected transactions</Text></Pressable><Text style={s.muted}>Processed on this device; statement file is not retained. Scanned PDFs are not supported yet.</Text></ScrollView></SafeAreaView></Modal>
<Modal visible={modal==='profile'} transparent animationType="fade" onRequestClose={()=>setModal('')}><View style={s.overlay}><View style={s.sheet}><Pressable onPress={()=>setModal('')}><Text style={s.close}>Close ×</Text></Pressable><Text style={s.title}>Your profile</Text><Text style={s.label}>NAME (OPTIONAL)</Text><TextInput style={s.input} value={d.name} onChangeText={v=>save({...d,name:v})} placeholder="Name"/><Text style={s.label}>BALANCE BEFORE YOUR RECORDED TRANSACTIONS (₹)</Text><TextInput style={s.input} keyboardType="decimal-pad" value={String(d.opening||0)} onChangeText={v=>{const opening=Number(v)||0;const flow=d.transactions.reduce((sum,t)=>sum+(t.kind==="income"?t.amount:-t.amount),0);save({...d,opening,cash:opening+flow});}}/><Text style={s.muted}>Records stay on this device. No bank login or credentials are requested.</Text></View></View></Modal>
</SafeAreaView></SafeAreaProvider>}
export default function Root(){return <App/>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f4f6f2'},header:{height:52,paddingHorizontal:19,borderBottomWidth:1,borderColor:'#e8ece6',flexDirection:'row',alignItems:'center',justifyContent:'space-between'},brand:{fontSize:10,letterSpacing:1,color:'#53665a',fontWeight:'700'},avatar:{padding:8,borderRadius:18,backgroundColor:'#e8ddca',color:'#604d3d'},body:{padding:18,paddingBottom:25},eyebrow:{fontSize:9,letterSpacing:1.2,fontWeight:'700',color:'#939c94',marginVertical:8},title:{fontSize:25,fontWeight:'700',color:'#25332a',marginVertical:6},title2:{fontSize:16,fontWeight:'700',color:'#354239',marginTop:15},muted:{fontSize:11,color:'#8b958d',lineHeight:18,marginVertical:5},card:{backgroundColor:'#fff',borderColor:'#e9ede7',borderWidth:1,borderRadius:12,padding:17,marginVertical:11},big:{fontSize:34,fontWeight:'700',color:'#26372c',marginVertical:8},line:{height:1,backgroundColor:'#edf0ec',marginVertical:12},label:{fontSize:10,color:'#69766d',marginVertical:6},bold:{fontSize:12,fontWeight:'600',color:'#354138'},tx:{minHeight:54,flexDirection:'row',alignItems:'center',borderBottomWidth:1,borderColor:'#e9ede7',paddingVertical:8,gap:8},button:{height:44,borderRadius:8,backgroundColor:'#385443',alignItems:'center',justifyContent:'center',marginVertical:9},white:{color:'#fff',fontSize:12,fontWeight:'700'},outline:{height:44,borderRadius:8,borderWidth:1,borderColor:'#385443',alignItems:'center',justifyContent:'center',marginBottom:12},dark:{color:'#385443',fontSize:12,fontWeight:'600'},green:{color:'#63816a',fontWeight:'700'},nav:{height:55,backgroundColor:'#fff',borderTopWidth:1,borderColor:'#e7ebe5',flexDirection:'row',alignItems:'center',justifyContent:'space-around'},overlay:{flex:1,backgroundColor:'rgba(20,31,24,.38)',justifyContent:'flex-end'},sheet:{backgroundColor:'#fff',borderTopLeftRadius:18,borderTopRightRadius:18,padding:22,paddingBottom:Platform.OS==='ios'?34:22},close:{fontSize:13,color:'#627269',textAlign:'right',marginBottom:10},input:{minHeight:44,borderRadius:7,borderWidth:1,borderColor:'#e4e9e3',paddingHorizontal:12,marginVertical:7,fontSize:13,color:'#354138'},importRow:{flexDirection:'row',alignItems:'center',gap:8,paddingVertical:8,borderBottomWidth:1,borderColor:'#e9ede7'},check:{fontSize:20,color:'#385443'},editInput:{padding:2,fontSize:12,color:'#354138',fontWeight:'600'}});

